version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_USERNAME: pdb
      MYSQL_PASSWORD: pdbpass
      MYSQL_ROOT_PASSWORD: pdbpass
      MYSQL_DATABASE: pdb
  b:
    depends_on:
    - db
    image: test
    ports:
    - "8000:8080"
    restart: always
    profiles: container
    datasource:
      url: jdbc:mysql://mysql:3306/pdb
      username: pdb
      password: pdbpass
      driver-class-name: com.mysql.jdbc.Driver
    environment:
      MYSQL_HOST: db:3306
      SPRING_DB_HOST: db:3306
      OPENJDK_DB_HOST: db:3306	  
      SPRING_DATASOURCE_URL=jdbc:mysql://pdb/quotes?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME=pdb
      SPRING_DATASOURCE_PASSWORD=pdbpass
  f:
    depends_on:
    - db
    - b
    image: coscicorp/catalog_frontend
    ports: 
    - "80:3000"
    restart: always
volumes:
  db_data: {}